# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_license_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("renewal", "Renewal"),
                    ("upgrade", "Upgrade"),
                    ("downgrade", "Downgrade"),
                ],
                default="initial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("revoked", "Revoked"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
