# Generated by Django 5.1.4 on 2026-07-06 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0009_remove_membership_uniq_iam_user_org_and_more"),
        ("node", "0004_alter_nodetoken_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LensKnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "backup_source_snapshot_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("source_path", models.CharField(max_length=500)),
                (
                    "mount_path_on_gateway",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "workspace_path_on_lensnode",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "linked_version_mode",
                    models.CharField(
                        choices=[("latest", "Latest"), ("pinned", "Pinned")],
                        default="latest",
                        max_length=16,
                    ),
                ),
                ("pinned_snapshot_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "sl_assistant_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "sl_lensnode_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("provisioning", "Provisioning"),
                            ("learning", "Learning"),
                            ("ready", "Ready"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("status_detail", models.TextField(blank=True, default="")),
                ("scan_enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lens_knowledge_sources_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lens_knowledge_sources",
                        to="node.node",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lens_bridge_knowledge_source",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LensOrgLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("default_lensnode_uuid", models.UUIDField(blank=True, null=True)),
                ("default_agent_model_ref", models.UUIDField(blank=True, null=True)),
                (
                    "assistant_name_prefix",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lens_bridge_org_link",
            },
        ),
        migrations.CreateModel(
            name="LensSessionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "sl_session_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "sl_assistant_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "hfl_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lens_session_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "knowledge_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_links",
                        to="lens_bridge.lensknowledgesource",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lens_bridge_session_link",
                "ordering": ["-last_message_at", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LensGatewayLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "sl_lensnode_uuid",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "workspace_root",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "sidecar_status",
                    models.CharField(
                        choices=[
                            ("not_deployed", "Not deployed"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="not_deployed",
                        max_length=20,
                    ),
                ),
                ("config_json", models.JSONField(blank=True, default=dict)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lens_gateway_links",
                        to="node.node",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lens_bridge_gateway_link",
                "indexes": [
                    models.Index(
                        fields=["organization", "sidecar_status"],
                        name="lens_brgw_org_st_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "gateway"),
                        name="uniq_lens_bridge_gw_link_org_gw",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lensknowledgesource",
            index=models.Index(
                fields=["organization", "status", "created_at"],
                name="lens_bks_org_st_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lensknowledgesource",
            index=models.Index(
                fields=["organization", "gateway"], name="lens_bks_org_gw_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lensorglink",
            constraint=models.UniqueConstraint(
                fields=("organization",), name="uniq_lens_bridge_org_link_org"
            ),
        ),
        migrations.AddIndex(
            model_name="lenssessionlink",
            index=models.Index(
                fields=["organization", "hfl_user", "status"],
                name="lens_bsess_org_user_st_idx",
            ),
        ),
    ]
