# Generated by Django 5.1.4 on 2026-07-06 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0009_remove_membership_uniq_iam_user_org_and_more"),
        ("lens_bridge", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LensOrgModelLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sl_config_uuid", models.UUIDField(db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lens_org_model_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "db_table": "lens_bridge_org_model_link",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="lens_borgmdl_org_cr_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "sl_config_uuid"),
                        name="uniq_lens_bridge_org_model_org_uuid",
                    ),
                    models.UniqueConstraint(
                        fields=("sl_config_uuid",),
                        name="uniq_lens_bridge_org_model_uuid",
                    ),
                ],
            },
        ),
    ]
