# Generated by Django 5.1.4 on 2026-07-08 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0009_remove_membership_uniq_iam_user_org_and_more"),
        ("lens_bridge", "0008_lens_assistant_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="lensassistantlink",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="lensassistantlink",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iam.organization"
            ),
        ),
    ]
