# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens_bridge", "0019_lensorgmodellink_management_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lensgatewaylink",
            name="sidecar_status",
            field=models.CharField(
                choices=[
                    ("not_deployed", "Not deployed"),
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("upgrading", "Upgrading"),
                    ("removing", "Removing"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="not_deployed",
                max_length=20,
            ),
        ),
    ]
