# Generated by Django 5.1.4 on 2026-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node", "0003_node_role_agent_proxy_gateway"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodetoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
