# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("audit", "0004_audit_log_xxz_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                        '"audit_logs_resource_id_538549f1" '
                        'ON "audit_logs" ("resource_id");'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY IF EXISTS "
                        '"audit_logs_resource_id_538549f1";'
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "CREATE INDEX CONCURRENTLY IF NOT EXISTS "
                        '"audit_logs_resource_id_538549f1_like" '
                        'ON "audit_logs" ("resource_id" varchar_pattern_ops);'
                    ),
                    reverse_sql=(
                        "DROP INDEX CONCURRENTLY IF EXISTS "
                        '"audit_logs_resource_id_538549f1_like";'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="auditlog",
                    name="resource_id",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                    ),
                ),
            ],
        ),
    ]
