# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_config", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalconfig",
            options={
                "ordering": ["category", "key", "scope", "tenant_key", "id"],
                "verbose_name": "Global Configuration",
                "verbose_name_plural": "Global Configurations",
            },
        ),
    ]
