#!/usr/bin/env python3
"""Materialize HFL_EXTENSION_SOURCES → HFL_EXTENSIONS and emit compose overlay.

Used by ``dev/stack.sh``. Runtime processes only see local paths.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


def _split_list(raw: str) -> list[str]:
    return [p.strip() for p in raw.split(",") if p.strip()]


def _read_id(root: Path) -> str:
    toml = root / "extension.toml"
    if toml.is_file():
        text = toml.read_text(encoding="utf-8")
        m = re.search(r'(?m)^\s*id\s*=\s*["\']([^"\']+)["\']', text)
        if m:
            return m.group(1).strip()
    name = root.name.strip()
    if name.startswith("hyperfilelens-"):
        name = name[len("hyperfilelens-") :]
    return name or "extension"


def _looks_like_root(root: Path) -> bool:
    return (root / "src" / "backend").is_dir()


def _parse_source(item: str) -> tuple[str, str | None]:
    """Return (location, git_ref). location is path or git URL."""
    if item.startswith("git@") or item.startswith("http://") or item.startswith("https://"):
        if "@" in item.rsplit(":", 1)[-1] and not item.startswith("git@"):
            # https://host/repo.git@ref
            url, _, ref = item.rpartition("@")
            return url, ref or None
        if item.startswith("git@") and item.count("@") >= 2:
            # git@host:org/repo.git@ref
            url, _, ref = item.rpartition("@")
            return url, ref or None
        return item, None
    if "://" in item and "@" in item:
        url, _, ref = item.rpartition("@")
        return url, ref or None
    return item, None


def _clone(url: str, dest: Path, ref: str | None) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if dest.exists():
        subprocess.check_call(["git", "-C", str(dest), "fetch", "--all", "--tags"], stdout=subprocess.DEVNULL)
        if ref:
            subprocess.check_call(["git", "-C", str(dest), "checkout", ref], stdout=subprocess.DEVNULL)
            subprocess.check_call(
                ["git", "-C", str(dest), "pull", "--ff-only"],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        return
    cmd = ["git", "clone", "--depth", "1"]
    if ref:
        cmd += ["--branch", ref]
    cmd += [url, str(dest)]
    subprocess.check_call(cmd)


def materialize(sources: list[str], cache_dir: Path) -> list[Path]:
    roots: list[Path] = []
    for item in sources:
        location, ref = _parse_source(item)
        if location.startswith("git@") or "://" in location:
            # Dest folder name from repo basename
            base = location.rstrip("/").rsplit("/", 1)[-1]
            if base.endswith(".git"):
                base = base[:-4]
            dest = cache_dir / base
            _clone(location, dest, ref)
            root = dest.resolve()
        else:
            root = Path(location).expanduser().resolve()
        if not _looks_like_root(root):
            raise SystemExit(f"not an extension root (missing src/backend): {root}")
        roots.append(root)
    return roots


def write_compose(out: Path, mounts: list[tuple[str, Path]]) -> None:
    """mounts: (container_path, host_path)."""
    lines = [
        "# Generated by tools/extensions/materialize_extensions.py — do not edit.",
        "# Loaded by stack.sh when HFL_EXTENSION_SOURCES / HFL_EXTENSIONS is set.",
        "services:",
    ]
    env_val = ",".join(c for c, _ in mounts)
    vol_lines = []
    for container, host in mounts:
        vol_lines.append(f"      - {host}:{container}:ro")
        # Frontend live-reload for Vite when src/frontend exists
        fe = host / "src" / "frontend" / "src"
        if fe.is_dir():
            vol_lines.append(f"      - {fe}:{container}/src/frontend/src:ro")

    # Deduplicate volume lines while preserving order
    seen: set[str] = set()
    uniq_vols: list[str] = []
    for v in vol_lines:
        if v in seen:
            continue
        seen.add(v)
        uniq_vols.append(v)

    block = [
        "    environment:",
        f'      HFL_EXTENSIONS: "{env_val}"',
        "    volumes:",
        *uniq_vols,
    ]
    for svc in ("api", "worker", "scheduler"):
        lines.append(f"  {svc}:")
        lines.extend(block)
    lines.append("  ui:")
    lines.extend(block)
    lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--sources", default=os.getenv("HFL_EXTENSION_SOURCES", ""))
    parser.add_argument("--extensions", default=os.getenv("HFL_EXTENSIONS", ""))
    parser.add_argument(
        "--compose-out",
        type=Path,
        default=None,
        help="Write docker-compose overlay (default: <repo>/build/docker-compose.extensions.yml)",
    )
    parser.add_argument(
        "--print-extensions",
        action="store_true",
        help="Print container HFL_EXTENSIONS value to stdout",
    )
    args = parser.parse_args()
    repo = args.repo_root.resolve()
    cache = repo / "build" / "extensions"
    compose_out = args.compose_out or (repo / "build" / "docker-compose.extensions.yml")

    sources = _split_list(args.sources)
    extensions = _split_list(args.extensions)

    if sources:
        host_roots = materialize(sources, cache)
    elif extensions:
        host_roots = []
        for p in extensions:
            root = Path(p).expanduser().resolve()
            if not _looks_like_root(root):
                raise SystemExit(f"not an extension root: {root}")
            host_roots.append(root)
    else:
        if compose_out.exists():
            compose_out.unlink()
        if args.print_extensions:
            print("")
        return 0

    mounts: list[tuple[str, Path]] = []
    seen_ids: set[str] = set()
    for root in host_roots:
        ext_id = _read_id(root)
        if ext_id in seen_ids:
            raise SystemExit(f"duplicate extension id: {ext_id}")
        seen_ids.add(ext_id)
        container = f"/opt/hfl/extensions/{ext_id}"
        mounts.append((container, root))

    write_compose(compose_out, mounts)
    container_list = ",".join(c for c, _ in mounts)
    if args.print_extensions:
        print(container_list)
    print(f"extensions: {len(mounts)} → {compose_out}", file=sys.stderr)
    for c, h in mounts:
        print(f"  {c} <= {h}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
