# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restore", "0003_restore_plan_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restorerecorditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
    ]
