# Generated by Django 5.1.4 on 2026-05-14 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iam', '0002_membership_preferred_feature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFABypassToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_mfa_bypass_token',
            },
        ),
        migrations.CreateModel(
            name='MFACredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(max_length=64)),
                ('issuer_label', models.CharField(default='HyperFileLens', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iam_mfa_credential',
            },
        ),
        migrations.CreateModel(
            name='MFARecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_mfa_recovery_code',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_completed', models.BooleanField(default=False)),
                ('registration_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('registration_token_expires', models.DateTimeField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('avatar_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('language', models.CharField(choices=[('en', 'English')], default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('preferred_platform', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable role name.', max_length=120, unique=True)),
                ('visible_features', models.JSONField(blank=True, default=list, help_text='Feature keys visible to users who hold this role.')),
                ('preferred_platform', models.CharField(blank=True, default='', help_text='Default platform to open after login.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role participates in access calculation.')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='iam_members_organiz_329c5d_idx',
            old_name='iam_member_organiza_9f4e5f_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='mfa_enforced',
            field=models.BooleanField(default=False, help_text='Enable to require MFA for members with specific roles.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mfa_enforced_roles',
            field=models.JSONField(default=list, help_text="List of roles that must have MFA enabled when mfa_enforced is True. Example: ['owner', 'admin']"),
        ),
        migrations.AddField(
            model_name='mfabypasstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_bypass_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfacredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_credential', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mfarecoverycode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_recovery_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups whose members inherit this role.', related_name='platform_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users directly bound to this role.', related_name='platform_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mfarecoverycode',
            index=models.Index(fields=['user', 'is_used'], name='iam_mfa_rec_user_id_12899f_idx'),
        ),
    ]
