# Generated by Django 5.1.4 on 2026-05-15 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_mfabypasstoken_mfacredential_mfarecoverycode_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAEmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_mfa_email_code',
                'indexes': [models.Index(fields=['user', 'is_used', 'expires_at'], name='iam_mfa_ema_user_id_a0b648_idx')],
            },
        ),
    ]
