# Generated by Django 5.1.4 on 2026-06-18 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_remove_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_email_verification_code',
            },
        ),
        migrations.RemoveField(
            model_name='mfabypasstoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mfacredential',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mfaemailcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mfarecoverycode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mfa_enforced',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mfa_enforced_roles',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('role', 'owner')), fields=('organization',), name='uniq_iam_org_active_owner'),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MFABypassToken',
        ),
        migrations.DeleteModel(
            name='MFACredential',
        ),
        migrations.DeleteModel(
            name='MFAEmailCode',
        ),
        migrations.DeleteModel(
            name='MFARecoveryCode',
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='iam_email_v_user_id_426646_idx'),
        ),
    ]
