# Generated by Django 5.1.4 on 2026-07-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0008_remove_mfa_and_owner_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="uniq_iam_user_org",
        ),
        migrations.AlterField(
            model_name="profile",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default="en",
                max_length=10,
            ),
        ),
    ]
