# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source", "0004_repository_purge_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceresource",
            name="mount_status",
            field=models.CharField(
                choices=[
                    ("unmounted", "Unmounted"),
                    ("mounted", "Mounted"),
                    ("error", "Mount Error"),
                ],
                default="unmounted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourceresource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("nas", "NAS"),
                    ("nfs", "NFS"),
                    ("cifs", "CIFS/SMB"),
                    ("s3", "Object Storage"),
                    ("local", "Local Filesystem"),
                ],
                db_index=True,
                default="nfs",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sourceresource",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
