# Generated by Django 5.1.4 on 2026-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_rename_notification_tables"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationdelivery",
            new_name="notif_del_org_status_cr_idx",
            old_name="notification_del_organ_5a47c0_idx",
        ),
        migrations.AlterField(
            model_name="notificationchannel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("webhook", "Webhook"),
                    ("dingtalk", "DingTalk"),
                    ("wecom", "WeCom"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
