"""IAM policy defaults (overridable via GlobalConfig)."""

CONFIG_KEY_REGISTRATION_TOKEN_EXPIRY_HOURS = "iam.registration.token_expiry_hours"
CONFIG_KEY_PASSWORD_RESET_TIMEOUT = "iam.password_reset.timeout_seconds"
CONFIG_KEY_REGISTRATION_CODE_MINUTES = "iam.registration.verification_code_minutes"
CONFIG_KEY_PASSWORD_RESET_CODE_MINUTES = "iam.password_reset.verification_code_minutes"

DEFAULT_REGISTRATION_TOKEN_EXPIRY_HOURS = 24
DEFAULT_PASSWORD_RESET_TIMEOUT_SECONDS = 86400
DEFAULT_REGISTRATION_VERIFICATION_CODE_MINUTES = 15
DEFAULT_PASSWORD_RESET_VERIFICATION_CODE_MINUTES = 15
